### ISSUE TITLE
Python plugin doesn't work in KiCad 7

### ISSUE THREAD

**Issue by Pe8er** [skarrmann/horizon#5]
Hi!

[I'm making an attempt](https://github.com/Pe8er/horizon-mini/tree/main/kicad/choc) to reduce the size of your fantastic design to 10 columns. However, the board producer plugin throws the following error in KiCad 7:

```
Traceback (most recent call last):

File "/Users/pe8er/Documents/KiCad/7.0/3rdparty/plugins/horizon-board-producer-plugin.py", line 20, in Run
HorizonBoardProducerPlugin.produce()

File "/Users/pe8er/Documents/KiCad/7.0/3rdparty/plugins/horizon-board-producer-plugin.py", line 248, in produce
HorizonBoardProducerPlugin.__create_gerbers(pcb, gerber_output_path)

File "/Users/pe8er/Documents/KiCad/7.0/3rdparty/plugins/horizon-board-producer-plugin.py", line 41, in __create_gerbers
plot_options.SetExcludeEdgeLayer(True)

AttributeError: 'PCB_PLOT_PARAMS' object has no attribute 'SetExcludeEdgeLayer'
```

Any chance you could fix it please? Thanks a ton!

**Comment by skarrmann** [comment]
Hello!

Yes, I will try migrating the board generator plugin code to KiCad 7 within the next couple days. It was last migrated to KiCad 6, so it needs to be updated again.

I will let you know how it goes.

**Comment by Pe8er** [comment]
Thanks and good luck!

**Comment by skarrmann** [comment]
Thanks!

Can you please try running this updated plugin code in KiCad 7? https://github.com/skarrmann/horizon/blob/ec8f4e240b31b75347d11e4e73a34dd3b1617870/kicad-plugins/horizon-board-producer-plugin.py

I confirmed the update works for me on KiCad 7.0.9. Please note KiCad will forcefully close after the plugin successfully runs. You should see this message if the plugin successfully generated the fabrication files:

![kicad-7-horizon-board-producer-complete-message](https://github.com/skarrmann/horizon/assets/697412/6fc8caa1-0cf7-426e-9397-82731cb8958c)

Let me know if this updated code works for you. If it's good, I will merge this update into the main project. Thank you!

**Comment by Pe8er** [comment]
It works on KiCad 7.0.8 on Mac, and the script kills KiCad at the end. I reviewed the gerbers as best as I could, they looked fine so I just submitted an order 😀 Thank you so much!

**Comment by skarrmann** [comment]
Great! Thank you for testing this update.

Good luck with your Horizon Mini, and I'd love to hear how the build goes.

**Comment by Pe8er** [comment]
I will let you know for sure, hopefully it works 🤞

**Comment by Pe8er** [comment]
@skarrmann Hey! It is alive! 😀 Thank you for brilliant idea and design!

![horizon-mini](https://github.com/skarrmann/horizon/assets/770120/81aa5402-0c85-4a85-aed4-a1d518537d4a)

There is just one remaining issue: it seems like the battery is not charging. I don't know if the battery is broken or is it something with my soldering, or maybe ZMK. I'm off to get help on ZMK Discord.

**Comment by skarrmann** [comment]
Your board looks fantastic, congratulations!

Good luck with the battery charging issue. I'm sure the ZMK Discord help you with troubleshooting.
